name: Dev ADF Deployment

on:
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
  actions: read

env:
  DEV_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  DEV_RESOURCE_GROUP: mayurr-rg
  DEV_ADF_NAME: adf-shr-dev
  PROD_RESOURCE_GROUP: mayurr-rg
  PROD_ADF_NAME: adf-shr-prod
  PROD_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
        
      - name: Install ADF Utilities package
        run: npm install
        working-directory: ${{ github.workspace }}
        
      - name: Validate ADF Configuration
        run: npm run build validate ${{ github.workspace }}/ /subscriptions/${{ env.DEV_SUBSCRIPTION_ID }}/resourceGroups/${{ env.DEV_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ env.DEV_ADF_NAME }}
        working-directory: ${{ github.workspace }}
  
      - name: Generate ARM Templates
        run: npm run build export ${{ github.workspace }}/ /subscriptions/${{ env.DEV_SUBSCRIPTION_ID }}/resourceGroups/${{ env.DEV_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ env.DEV_ADF_NAME }} "ExportedArmTemplate"
        working-directory: ${{ github.workspace }}
  
      - name: Upload ARM Templates
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/ExportedArmTemplate

  dev_release:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Run PowerShell command
        shell: pwsh
        run: Write-Output "PowerShell Core is working!"

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate 

      - name: Login to Azure
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.DEV_SUBSCRIPTION_ID }}
        
      - name: Before Deployment Script
        shell: pwsh
        run: pwsh -Command Connect-AzAccount -Identity

      - name: Run Pre-Deployment Script
        shell: pwsh
        run: |
          sudo pwsh -Command ./PrePostDeploymentScript.ps1 `
            -armTemplate "./ARMTemplateForFactory.json" `
            -armTemplateParameters "./ARMTemplateParametersForFactory.json" `
            -ResourceGroupName "${{ env.DEV_RESOURCE_GROUP }}" `
            -DataFactoryName "${{ env.DEV_ADF_NAME }}" `
            -predeployment 1 `
            -deleteDeployment 0

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.6
        with:
          scope: 'resourcegroup'
          resourceGroupName: ${{ env.DEV_RESOURCE_GROUP }}
          template: ./ARMTemplateForFactory.json
          deploymentMode: Incremental
          parameters: ./ARMTemplateParametersForFactory.json
      #       factoryName=${{ env.DEV_ADF_NAME }}
      #       AzureDataLakeStorage1_accountKey=${{ secrets.ADL_STORAGE_KEY }}
      #       linkedservice2adls_prod_accountKey=${{ secrets.ADL_PROD_STORAGE_KEY }}
      #       AzureDataLakeStorage1_properties_typeProperties_url=https://stadlsudpdwhwcmprodsea01.dfs.core.windows.net/
      #       linkedservice2adls_prod_properties_typeProperties_url=https://stadlsudpdwhwcmprodsea01.dfs.core.windows.net/
      #       linkservice2adls_properties_typeProperties_url=https://udpdatawarehousedev.dfs.core.windows.net/
      #       linkservice2dbr_wcm_properties_typeProperties_existingClusterId=0226-111118-84xlg58u
      #       linkservice2gcs_properties_typeProperties_accessKeyId=${{ secrets.GCS_ACCESS_KEY }}
      #       linkservice2keyvault_properties_typeProperties_baseUrl=https://udp-datawarehouse-dev.vault.azure.net/
      #       linkservice2ropdataportal_properties_typeProperties_host=udpdatawarehousedev.blob.core.windows.net
      #       linkservice2ropdataportal_properties_typeProperties_userName=udpdatawarehousedev.ropdataportal
      #       linkservice2saptable_plhs4_properties_typeProperties_clientId=500
      #       linkservice2saptable_plhs4_properties_typeProperties_userName=RFCUSR_UDP
      #       linkservice2saptable_plhs4_properties_typeProperties_server=10.100.128.36
      #       linkservice2saptable_plhs4_properties_typeProperties_systemNumber=00
      #       linkservice2saptable_wcmecc_properties_typeProperties_clientId=301
      #       linkservice2saptable_wcmecc_properties_typeProperties_userName=RFCUSR_UDP
      #       linkservice2saptable_wcmecc_properties_typeProperties_server=10.235.52.11
      #       linkservice2saptable_wcmecc_properties_typeProperties_systemNumber=00
      #       linkservice2saptablebw_properties_typeProperties_clientId=400
      #       linkservice2saptablebw_properties_typeProperties_userName=RFCUSR_UDP
      #       linkservice2saptablebw_properties_typeProperties_server=10.235.52.51
      #       linkservice2saptablebw_properties_typeProperties_systemNumber=00
      #       linkservice2sftpsap_properties_typeProperties_host=udpdatawarehousedev.blob.core.windows.net
      #       linkservice2sftpsap_properties_typeProperties_userName=udpdatawarehousedev.udpdev
      #       linksevice2saptable_wececc_properties_typeProperties_clientId=709
      #       linksevice2saptable_wececc_properties_typeProperties_userName=RFCUSR_UDP
      #       linksevice2saptable_wececc_properties_typeProperties_server=10.235.53.21
      #       linksevice2saptable_wececc_properties_typeProperties_systemNumber=00

      - name: Deploy ADF using Data Factory Deploy Action
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ env.DEV_RESOURCE_GROUP }}  # Target ADF Resource Group
          dataFactoryName: ${{ env.DEV_ADF_NAME }}  
          armTemplateFile: ${{ github.workspace }}/ARMTemplateForFactory.json  
          armTemplateParametersFile: ${{ github.workspace }}/ARMTemplateParametersForFactory.json
          skipAzModuleInstallation: 'true'

      - name: Run Post-deployment Script
        shell: pwsh
        run: |
          sudo pwsh -Command ./PrePostDeploymentScript.ps1 `
            -armTemplate "./ARMTemplateForFactory.json" `
            -armTemplateParameters "./ARMTemplateParametersForFactory.json" `
            -ResourceGroupName "${{ env.DEV_RESOURCE_GROUP }}" `
            -DataFactoryName "${{ env.DEV_ADF_NAME }}" `
            -predeployment 0 `
            -deleteDeployment 1

  

